### ISSUE TITLE
Deprovision site and redirect traffic to outreach.uiowa.edu

### ISSUE THREAD

**Issue by joewhitsitt** [ITS-UofIowa/artshare.uiowa.edu#3]
This site is no longer being used and all related information is now at outreach.uiowa.edu.

https://wiki.uiowa.edu/display/sitenow/Deprovisioning+a+Custom+site+on+Acquia+Cloud

For the redirect, the artshare entry should be removed from the https://github.com/ITS-UofIowa/drupal-manifest/blob/master/.sites.yml but a redirect should be added to the outreach.uiowa.edu entry.

**Comment by cory-skeers** [comment]
Site deprovisioned, redirect in place.
